spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: prod
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      uri: http://localhost:8888
      username: root
      password: s3cr3t
  config:
    import: configserver:http://localhost:8888

