spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: dev
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      uri: http://localhost:8888
      username: root
      password: s3cr3t
      fail-fast: true
