spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: prod
  cloud:
    config:
      name: kafka-to-elastic-service,config-client
      username: root
      password: s3cr3t
      fail-fast: true
